export type PublicEntryRow = {
  public_id: string // UUID generated by the database
  title: string
  message: string
  created_at: string // ISO 8601 timestamp from Postgres
}

export type Entry = {
  // The frontend id is always the database-generated public_id.
  id: string
  title: string
  message: string
  createdAt: string // camelCase mirror of created_at
  local?: boolean // true only for entries submitted in this browser session
}
